[Journal]
Storage=persistent
Compress=yes
Seal=yes
SyncIntervalSec=30s
SystemMaxUse=256M
SystemMaxFileSize=32M
SystemKeepFree=512M
MaxRetentionSec=14day
MaxFileSec=1day
RateLimitIntervalSec=30s
RateLimitBurst=500
