include:
  file: trixie-minbase-ab.yaml

device:
  layer: rpi5
  hostname: showroom
  user1: pi
  user1sudo: passwd
  user1groups: adm,dialout,cdrom,audio,users,video,games,plugdev,input,spi,i2c,gpio,render

ssh:
  pubkey_only: y

artefact:
  version: 1.0.0

image:
  name: showroom-appliance
  boot_part_size: 192M
  system_part_size: 2400M
  data_part_size: 12G
  rootfs_type: erofs

layer:
  base: trixie-showroom-base
  app: showroom-appliance

ieee80211:
  regdom: US
